### ISSUE TITLE
Queueing closures

### ISSUE THREAD

**Issue by damsfx** [wintercms/docs#16]
I was just trying queueing closure according to the [documentation](https://github.com/wintercms/docs/blob/main/services-queues.md#queueing-closures), but falling in an "Closure object cannot have properties" error.
After a quick search, it look like Laravel  dind't even support queueing closure since v5.3.0 [release note](https://laravel.com/docs/5.3/upgrade#upgrade-5.3.0).

**Comment by LukeTowers** [comment]
@bennothommo do you think we should fix support or update the docs for this case?

**Comment by bennothommo** [comment]
@damsfx @LukeTowers queuing closures was brought back it seems. It can be done in Laravel 6 - https://laravel.com/docs/6.x/queues#queueing-closures. The issue is that you can't have any properties - you must instead pass through the variables you need through the `use` statement.

We'd just need to update our docs to show an example without any properties.
